### ISSUE TITLE
Breadcrumb

### ISSUE THREAD

**Issue by congthien** [PressMaximum/customify#114]
When I select the breadcrumb display inside the Page Cover/Titlebar. If I disable the page title, the breadcrumb is gone too.

**Comment by congthien** [comment]
And missing color for character: https://cl.ly/3C0w23323n0P

**Comment by shrimp2t** [comment]
You should set breadcrumb colors too https://cl.ly/0m2z2E2K2Y2d

**Comment by congthien** [comment]
@shrimp2t 
For example I set the breadcrumb color is black, it works well inside Titlebar, but look not good in Cover. Is there any different setting to change in this case?
