### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '[' in /wp-content/themes/customify/inc/class-customify.php on line 532

### ISSUE THREAD

**Issue by github-media-support** [PressMaximum/customify#116]
Just after updating from 0.1.0 to 0.1.1 my test site went down with parse error:
PHP Parse error:  syntax error, unexpected '[' in /home/msupport/public_html/rtfc/wp-content/themes/customify/inc/class-customify.php on line 532

Same found for duke.sk but it was somehow fixed.

Any thoughts highly apreciated. 
Kr,
Jacek

**Comment by shrimp2t** [comment]
Hi, 

I fixed and it will available on next version.
This error occur when your PHP version to low (under `5.6.20`).
check system requirements https://wordpress.org/about/requirements/
