### ISSUE TITLE
Typekit integration

### ISSUE THREAD

**Issue by nickmadedesign** [PressMaximum/customify#120]
Hello :)

Do you have any advice for integrating Typekit — ideally, into the customizer?

I understand those types of font services, e.g. TypeKit, Fonts.com, etc., can be integrated via js/CSS selectors, but for the sake of trying to use the theme's typography customizer settings, I was hoping there was a better + more logical option.

Thank you, and keep up the great work!

**Comment by shrimp2t** [comment]
Hi,

At this time Customify theme not support custom fonts. But it support custom icons, you can add your custom icons by using this hook: `customify/customizer/font_icons`

See
https://github.com/PressMaximum/customify/blob/master/inc/customizer/class-customizer-icons.php#L34

**Comment by shrimp2t** [comment]
This option added in Customify Pro plugin, see https://wpcustomify.com/help/documentation/customify-pro-modules/typekit-fonts/
