### ISSUE TITLE
PHP Warning "call_user_func_array() expects parameter 1 to be a valid callback"

### ISSUE THREAD

**Issue by hiranthi** [PressMaximum/customify#128]
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Customify_Pro_Updater' does not have a method 'check_update' in /.../public_html/wp-includes/class-wp-hook.php on line 288

**Comment by KienTrong** [comment]
@shrimp2t Anything else for this?

**Comment by shrimp2t** [comment]
This issue for Customify Pro plugin and fixed in version `0.0.2` and this will release soon.
