### ISSUE TITLE
Placeholder-default for colors field in Customizer.

### ISSUE THREAD

**Issue by KienTrong** [PressMaximum/customify#147]
The problem is that when the user going to Styling -> Global Colors to change theme colors settings, there is no default colors which make it's hard to know that colors is showing where. 
Of course, that's true because we don't define default values for these colors setting fields.

If define default colors, these fields will auto-generate inline CSS which already provide by the theme CSS file.

So we can make a key `placeholder-default` for Color fields:

- Show placeholder colors by default but don't generate inline CSS.
- Only generate inline CSS if the colors changed by the user is different with the placeholder-default color field.

**Comment by shrimp2t** [comment]
Use key `placeholder` for placeholder label

**Comment by KienTrong** [comment]
@shrimp2t That's good, but the colors should appear, that's the most important: https://cl.ly/2V011B1W0z39
