### ISSUE TITLE
Add the WooCommerce Product Search form on header builder

### ISSUE THREAD

**Issue by congthien** [PressMaximum/customify#203]

**Comment by shrimp2t** [comment]
https://github.com/PressMaximum/customify/commit/278ec9bbfbe0eed2a78b3fece762050e6a320107

**Comment by TruongTuyen** [comment]
https://github.com/PressMaximum/customify/commit/278ec9bbfbe0eed2a78b3fece762050e6a320107 https://github.com/FameThemes/customify-pro/commit/2b7a88f313a0f7dee14cd23c8837e19c2fc18e6c  https://github.com/FameThemes/customify-pro/commit/569179e957cbf1280948bba25542ac3a960468b2  https://github.com/PressMaximum/customify/commit/cc10eb3049ac9404ca8dcdea2c2e70ce0b4ec019 https://github.com/PressMaximum/customify/commit/e013d72f3eeee37214887ccc66d6bafb284e725b https://github.com/FameThemes/customify-pro/commit/d705478d54130c3d2968f0bbf9bb3b466489453a

**Comment by congthien** [comment]
Pro only.
