### ISSUE TITLE
Can't zoom the Customify theme on Chrome mobile

### ISSUE THREAD

**Issue by congthien** [PressMaximum/customify#238]
User reported:
It works well on Safari, but not on Chrome.

**Comment by TruongTuyen** [comment]
Change meta tag in head tag from: <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"> to <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=10.0, user-scalable=yes">

Or use plugin: https://wordpress.org/plugins/definitely-allow-mobile-zooming/
