### ISSUE TITLE
Gettext

### ISSUE THREAD

**Issue by Longkt** [PressMaximum/customify#261]
https://github.com/PressMaximum/customify/blob/master/inc/template-functions.php#L320

It should be `esc_attr__()`

**Comment by IanDelMar** [comment]
The screen reader text in line 319 should also be escaped.

**Comment by shrimp2t** [comment]
Hi @IanDelMar, The text in line 319 don't need to be escaped.

**Comment by IanDelMar** [comment]
Hi @shrimp2t, translations can be manipulated. So it's safer to escape them.
