### ISSUE TITLE
Pro - Warning message Multi Language Module

### ISSUE THREAD

**Issue by Longkt** [PressMaximum/customify#287]
Warning message from the client

`Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/clients/0da2063ecf2ca76286d2276b6b8715ca/web/wp-content/plugins/customify-pro/modules/multilingual/multilingual.php on line 227
`

`Note: In PHP the switch statement is considered a looping structure for the purposes of continue. continue behaves like break (when no arguments are passed). If a switch is inside a loop, continue 2 will continue with the next iteration of the outer loop.`
https://www.php.net/manual/en/control-structures.continue.php

Should we create a better code to cover this case?

**Comment by shrimp2t** [comment]
Fixed in Pro version.
