### ISSUE TITLE
PHP Warning:  Use of undefined constant

### ISSUE THREAD

**Issue by jpknz** [PressMaximum/customify#290]
The following warning occurs in the latest version (not sure about previous versions).

_PHP Warning:  Use of undefined constant REQUEST_URI - assumed 'REQUEST_URI' (this will throw an Error in a future version of PHP) in /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/customify/functions.php on line 73_

**Comment by shrimp2t** [comment]
Hi,

Please try to update to latest version.
Because, there is no REQUEST_URI here: https://github.com/PressMaximum/customify/blob/master/functions.php#L73
