### ISSUE TITLE
Keep the Header Builder v1 along with v2

### ISSUE THREAD

**Issue by Longkt** [PressMaximum/customify#296]
Since version 0.3 release, the header builder v1 no longer available/support, some customers want to use v1 and say that it better than v2.

`Maybe the developer team bring back the header builder v1. V1 is much better than v2.`

**Comment by shrimp2t** [comment]
You can enable header builder version switcher by use the code below:
```php
add_filter( 'customify_hide_header_builder_switcher' , function(){
  return 'no'; // `no` to hide version switcher and `yes` to show it.
});
```

**Comment by shrimp2t** [comment]
If you want to change default header builder version just add the filter:

add_filter( 'header_builder_version' , function( $ver ){
  return 'v2'; // or `v1`
});
