### ISSUE TITLE
Function prefix Issue

### ISSUE THREAD

**Issue by sakinshrestha** [PressMaximum/customify#32]
* Spelling mistake on `comtomify_metabox_init()` in customify\inc\metabox.php line 6
* Some inconsistencies with function prefixes. Some have `Customify_` and some `customify_`, `customify_` being the proper one for function prefix according to WordPress coding standards. Change `Customify_` to `customify_` in following:
    * inc\posts\post-builder.php post-builder.php line: 300
    * inc\customizer-layout-builder\init.php line 452 and 1005

**Comment by shrimp2t** [comment]
Hi, if a function start with uppercase  like `Customify_` it is alias of class that class name. 
Example :
function `Customify_Init()` is alias of class `Customify_Init`
so we can call the method in class `Customify_Init` by using function `Customify_Init()`
```php
$more = Customify_Init()->excerpt_more();
```
Is this allowed by theme reviewers ?
