### ISSUE TITLE
Update version of Woocommerce template:

### ISSUE THREAD

**Issue by boy8xnoname** [PressMaximum/customify#360]
customify/woocommerce/cart/cart.php,
customify/woocommerce/cart/mini-cart.php,
customify/woocommerce/checkout/form-coupon.php,
customify/woocommerce/content-product.php,
customify/woocommerce/content-single-product.php,
customify/woocommerce/content-widget-product.php,
customify/woocommerce/content-widget-reviews.php,
customify/woocommerce/loop/add-to-cart.php,
customify/woocommerce/loop/loop-end.php,
customify/woocommerce/loop/loop-start.php,
customify/woocommerce/loop/pagination.php,
customify/woocommerce/loop/result-count.php,
customify/woocommerce/loop/sale-flash.php,
customify/woocommerce/product-searchform.php,
customify/woocommerce/single-product/add-to-cart/external.php,
customify/woocommerce/single-product/add-to-cart/grouped.php,
customify/woocommerce/single-product/add-to-cart/simple.php,
customify/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php,
customify/woocommerce/single-product/product-image.php,
customify/woocommerce/single-product/sale-flash.php,
customify/woocommerce/single-product/tabs/tabs.php,
customify/woocommerce/single-product/title.php

**Comment by shrimp2t** [comment]
it looks like all templates already updated.
