### ISSUE TITLE
Deprecated code warnings in PHP 8.1

### ISSUE THREAD

**Issue by boy8xnoname** [PressMaximum/customify#362]
I'm trying to get my sites / hosting environments up to at least PHP 8.1, but ideally PHP 8.2. I'm finding that I get the following warning when the WordPress debugger is turned on:

Deprecated: basename(): Passing null to parameter #1 ($path) of type string is deprecated in /home/s4hrrcs/public_html/wp-content/plugins/customify-pro/inc/class-module-base.php on line 47

Please advise if this will be addressed in a forthcoming update. Thank you!

**Comment by shrimp2t** [comment]
Pro plugin
