### ISSUE TITLE
[BUG] - Field to config product item per row doesn't work

### ISSUE THREAD

**Issue by boy8xnoname** [PressMaximum/customify#365]
Field to config product item per row on Tablet/Mobile doesn't work

![image](https://github.com/user-attachments/assets/780702fd-d4d4-4bec-9889-dc8ca00fbab0)

File path: customify/woocommerce/loop/loop-start.php

**Comment by shrimp2t** [comment]
I've tested with latest version it's working.

![image](https://github.com/user-attachments/assets/afb1ac10-68c5-407f-8b21-c77bfb0bf280)
![image](https://github.com/user-attachments/assets/6b52a1a7-9b33-49e5-98f3-05697b42b68f)
