### ISSUE TITLE
Design Issues: Footer Widgets

### ISSUE THREAD

**Issue by sakinshrestha** [PressMaximum/customify#39]
* It's not so flexible to. I just added Widget in Footer Widget 1 and Footer Widget 2. But it's showing demo Footer Widget 1 and Footer Widget 2. It's not the good experience. 
![footer-widgets](https://user-images.githubusercontent.com/9452203/37222793-6f617e8e-23f6-11e8-9174-32e7b80cb19a.png)
* Then I check in settings to remove Footer Widget 3 and Footer Widget 4. Finally I was able to remove it. But then, there is spacing issue. Check out this screenshot 
![footer-widget-spacing-issue](https://user-images.githubusercontent.com/9452203/37222897-d062c738-23f6-11e8-91a0-96a973d3322c.png)

**Comment by KienTrong** [comment]
In Footer layout builder area you can easily stretch the with of any widget or item.
