### ISSUE TITLE
More tag is being ignored in archive page

### ISSUE THREAD

**Issue by sakinshrestha** [PressMaximum/customify#45]
* I just added more tags in post and then check out archive page. But the more tag has been ignored and it's showing normal excerpt. 
* Check this screenshots
![more-tag](https://user-images.githubusercontent.com/9452203/37225782-d85069ba-23ff-11e8-8f36-9cefe9cd7786.png)
![ignores-more-tag](https://user-images.githubusercontent.com/9452203/37225789-dd86eeae-23ff-11e8-8def-14bbb81e333a.png)

**Comment by justintadlock** [comment]
Just noting that the theme calls the excerpt rather than the full post content on archive pages.  WordPress ignores the `<!--more-->` tag in this case.  This should be a non-issue.
