### ISSUE TITLE
Don't internationalize HTML if possible

### ISSUE THREAD

**Issue by justintadlock** [PressMaximum/customify#47]
In `template-parts/content.php` and `template-parts/content-page.php`, you have this bit of code:

```
the_content( sprintf(
	wp_kses(
		/* translators: %s: Name of current post. Only visible to screen readers */
		__( 'Continue reading<span class="screen-reader-text"> "%s"</span>', 'customify' ),
		array(
			'span' => array(
			'class' => array(),
			),
		)
	),
	get_the_title()
) );
```

The `<span>` mixed into the text string is entirely unnecessary and is causing you to add a lot of unneeded code.  It'd be far easier to use:

```
the_content(
        // Translators: %s: Name of current post. Only visible to screen readers.
        sprintf( esc_html__( 'Continue reading %s', 'customify' ), '<span class="screen-reader-text">' . the_title( '', '', false ) . '</span>' )
);
```

Also, note that I'm using `the_title()` rather than `get_the_title()` there so that all the right filters are applied.

**Comment by justintadlock** [comment]
I noticed this same issue in `inc/template-tags.php` with calls to `edit_post_link()`.

**Comment by shrimp2t** [comment]
Yes, i will make it easier.

I see  `the_title()` and `get_the_title()` functions are using same hook, that why i use `get_the_title` for none echoing content.

see https://core.trac.wordpress.org/browser/tags/4.9.2/src/wp-includes/post-template.php#L33
