### ISSUE TITLE
Recommended: Architecture redesign

### ISSUE THREAD

**Issue by justintadlock** [PressMaximum/customify#59]
For the most part, this looks like a solid theme in terms of code.  But, it's not _poetic_ code (referring to WordPress' motto of "code is poetry").  This is really the only thing I'd spend a lot of time trying to improve -- writing more maintainable code.  It's not something you need to address today.  It's something you'll work on over time.

Good inline docs is a start to making better code: https://github.com/PressMaximum/customify/issues/55

When I'm looking over theme code, a red flag for me is often seeing a file that's over 15 kb in size.  More often than not, this means the file needs to be broken down into separate files for better organization.  I touched on this in https://github.com/PressMaximum/customify/issues/53, but I'm creating this larger ticket because this is more about the entire theme code than just classes.

### Practical example of separating files

I'm going to give you a practical example of how I'd break down one of your large files.  Let's use `inc/customizer/customizer.php`.

First, I'd put the 3 classes into their own files. Something like:

* `class-customify-wp-customize-panel.php`
* `class-customify-wp-customize-section.php`
* `class-customify-customizer.php`.

Ideally, you'd use an autoloader to automatically load those (and any other classes) as needed.

Then, I'd separate all the functions into a file like:

* `functions-customizer.php`

Then, all the `require_once()` file loading calls, I'd separate out into its own file or section of another file for just loading stuff.  This should be a part of a bootstrap routine for the customizer somewhere.

The direct call to the `Customify_Customizer()` function should be a part of your customizer bootstrap routine too.

If you're interested in a really rough bootstrap method, feel free to check out one I'm currently building.  It's unfinished at the moment (need to move the `app()` function to a separate file too) and not specific to the customizer, but it may give you some ideas: https://github.com/justintadlock/abc/blob/master/bootstrap/app.php

### Arrays upon arrays 

A lot of your customizer code is arrays on top of more arrays.  It can't be easy to find stuff.

When I find myself in similar situations, I usually break a lot of the code out into its own function.

**Comment by KienTrong** [comment]
@justintadlock Hi Justin, thank you for this valuable recommended, I really appreciate it.

We have made the change to the theme follow your recommended, add some other small improvements and indeed it looks awesome now (WP PHP documentation standards is not done yet as we will improve it in the future release). Can you take a quick look at the DEV branch and give us some feedback, please?

Again, we really appreciate your help.
