### ISSUE TITLE
Precheck 2

### ISSUE THREAD

**Issue by congthien** [PressMaximum/customify#63]
- [ ] search box on mobile: https://cl.ly/2r2C2E2Z0n0N

- [x] if there is only a calendar in footer 1: https://cl.ly/0j1q3P0l462m  it is not displayed full width.

- [x] there is no sidebar layout for single post

- [x] When changing the  Footer HTML align, it changes the Header HTML align too.

- [x] the thumbnail no change because it is always 423*465px on frontpage: https://cl.ly/093n0F3u0I3Y

**Comment by shrimp2t** [comment]
single post sidebar is using blog posts sidebar
