### ISSUE TITLE
Duplicate the custom menu item

### ISSUE THREAD

**Issue by congthien** [PressMaximum/customify#89]
See, the Page Layouts & Page Builders are custom menu link and have submenu: 

![image](https://user-images.githubusercontent.com/5317804/39977392-e520916e-5763-11e8-86a4-30cff896f9b9.png)

**Comment by KienTrong** [comment]
@shrimp2t Not an issue and it's made on a purpose, this should be an option and No duplicate by default.

**Comment by KienTrong** [comment]
@shrimp2t Not sure if you have turn-on Github mention notification? we are working on multiple projects.
