### ISSUE TITLE
Improvement and fixes

### ISSUE THREAD

**Issue by Andres80** [PressMaximum/customify#96]
Good day,

Here some improvement and fixes you can work on:
- Improvement: Use the same background for the 3 menus as an option.
- Improvement: Activate transparent header only on Sticky header as an option
- Improvement: Improve Woocommerce Integration. 
- Fix: Some .php files have a space character at the begining of the file, giving issues when creating an XML site map.

**Comment by shrimp2t** [comment]
Thanks for you feedback, we'll try to find and fix your issues asap.

**Comment by KienTrong** [comment]
@shrimp2t Do you see anything for point 4?

**Comment by shrimp2t** [comment]
Point 4 not found issue
Tested:

- All In One SEO Pack
- Yoast SEO
- XML Sitemap & Google News feeds
- Google XML Sitemap Generator
- Google XML Sitemaps
